# -*- coding: utf-8 -*-
"""PalmerPenguinsM3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eLbjqSnGic5_FTXT70ox3xfodwDGVdRV
"""

# PalmerPenguinsM2.py
# Joseph Kurtz
# 10/2/2026
# Uses lists and formatted output to analyze Palmer Penguin statistics.

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

species_names = [SP_CHINSTRAP, SP_GENTOO, SP_ADELIE]
species_counts = [NUM_CHINSTRAP, NUM_GENTOO, NUM_ADELIE]

TOTAL_SPECIES = 3

import math

total_species = len(species_names)
total_penguins = sum(species_counts)
average_penguins = total_penguins / total_species
average_penguins_rounded_up = math.ceil(average_penguins)

chinstrap_percent = species_counts[0] / total_penguins * 100
gentoo_percentage = species_counts[1] / total_penguins * 100
adelie_percentage = species_counts[2] / total_penguins * 100

largest_count = max(species_counts)
smallest_count = min(species_counts)
largest_index = species_counts.index(largest_count)
smallest_index = species_counts.index(smallest_count)
largest_species = species_names[largest_index]
smallest_species = species_names[smallest_index]



# output the species names with introductory text
print("Introducing the Palmer Penguins:\n")

print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()
print(f"There are a total of {total_species} penguin species in the dataset.")
print(f"There are a total of {total_penguins} penguins in the dataset.")
print(f"The average number of penguins per species is {average_penguins:.1f}.")
print(f"The average rounded up is {average_penguins_rounded_up}.\n")

print(SP_CHINSTRAP + ":", NUM_CHINSTRAP, "(" + str(round(chinstrap_percentage, 2)) + "%)")
print(SP_GENTOO + ":", NUM_GENTOO, "(" + str(round(gentoo_percentage, 2)) + "%)")
print(SP_ADELIE + ":", NUM_ADELIE, "(" + str(round(adelie_percentage, 2)) + "%)\n")

print("The species with the most observations is", SP_ADELIE, "with", NUM_ADELIE, "penguins.")
print("The species with the fewest observations is", SP_CHINSTRAP, "with", NUM_CHINSTRAP, "penguins.")